name = "AlternatingConditionalExpectation"
uuid = "cdffec8e-cd60-4648-8609-4799fab23e96"
authors = ["nildt <mail@nwildt.de>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
