# Koopman-flavored demo: ACE on data generated by a nonlinear map.
#
# We observe a trajectory (x, ẋ) of the map x ↦ x² and ask ACE to find
# transformations Φ(x), Θ(ẋ) with Θ(ẋ) ≈ Φ(x).
#
# Run with:  julia --project=. scripts/demo_koopman.jl
# Saves:     output/demo_koopman_ace.png
using ACE
using LocalSmoothers
using Plots
ENV["GKSwstype"] = "100"  # headless

outdir = joinpath(@__DIR__, "..", "output")
mkpath(outdir)

f(x) = x^2
x = collect(range(1.0, 10.0, length=500))
xdot = f.(x)

# LASb over half the data: a smooth, monotone trend curve
smoother = LASb(length(xdot) ÷ 2)
sim = ACEsim(Matrix(reshape(x, :, 1)), Matrix(reshape(xdot, :, 1)), smoother;
             multiloopversion = :fresh, itermax_inner = 100, itermax_outer = 100,
             errorbound = 1e-5)
res = ACE.ace_run(sim)

@info "Koopman-style ACE result" ρ = res.ρ r² = res.r²[1] iters = res.itercount

path = joinpath(outdir, "demo_koopman_ace.png")
plot_ace_results(res; savepath = path)
println("saved -> ", path)
